 const StatesAndCities = [
    {
      id: 1,
      name: "Andhra Pradesh",
      hindi_name: "आंध्र प्रदेश",
    //   districts: [
    //     { id: 1, name: "Anantapur", hindi_name: "अनंतपुर" },
    //     { id: 2, name: "Chittoor", hindi_name: "चित्तूर" },
    //     { id: 3, name: "East Godavari", hindi_name: "पूर्वी गोदावरी" },
    //     { id: 4, name: "Guntur", hindi_name: "गुंटूर" },
    //     { id: 5, name: "Kadapa", hindi_name: "कडपा" },
    //     { id: 6, name: "Krishna", hindi_name: "कृष्णा" },
    //     { id: 7, name: "Kurnool", hindi_name: "कुरनूल" },
    //     { id: 8, name: "Nellore", hindi_name: "नेल्लोर" },
    //     { id: 9, name: "Prakasam", hindi_name: "प्रकाशम" },
    //     { id: 10, name: "Srikakulam", hindi_name: "श्रीकाकुलम" },
    //     { id: 11, name: "Visakhapatnam", hindi_name: "विशाखापत्तनम" },
    //     { id: 12, name: "Vizianagaram", hindi_name: "विजयनगरम" },
    //     { id: 13, name: "West Godavari", hindi_name: "पश्चिम गोदावरी" },
    //     { id: 14, name: "YSR Kadapa", hindi_name: "वाईएसआर कडपा" },
    //   ],
    },
    {
      id: 2,
      name: "Arunachal Pradesh",
      hindi_name: "अरुणाचल प्रदेश",
    //   districts: [
    //     { id: 1, name: "Tawang", hindi_name: "तवांग" },
    //     { id: 2, name: "West Kameng", hindi_name: "पश्चिम कामेंग" },
    //     { id: 3, name: "East Kameng", hindi_name: "पूर्वी कामेंग" },
    //     { id: 4, name: "Papum Pare", hindi_name: "पापुम पारे" },
    //     { id: 5, name: "Kurung Kumey", hindi_name: "कुरुंग कुमे" },
    //     { id: 6, name: "Kra Daadi", hindi_name: "क्रा दादी" },
    //     { id: 7, name: "Lower Subansiri", hindi_name: "निचला सुबनसिरी" },
    //     { id: 8, name: "Upper Subansiri", hindi_name: "ऊपरी सुबनसिरी" },
    //     { id: 9, name: "West Siang", hindi_name: "पश्चिम सियांग" },
    //     { id: 10, name: "East Siang", hindi_name: "पूर्वी सियांग" },
    //     { id: 11, name: "Siang", hindi_name: "सियांग" },
    //     { id: 12, name: "Upper Siang", hindi_name: "ऊपरी सियांग" },
    //     { id: 13, name: "Lower Siang", hindi_name: "निचला सियांग" },
    //     { id: 14, name: "Dibang Valley", hindi_name: "डिबांग घाटी" },
    //     { id: 15, name: "Lower Dibang Valley", hindi_name: "निचली डिबांग घाटी" },
    //     { id: 16, name: "Anjaw", hindi_name: "अंजॉ" },
    //     { id: 17, name: "Lohit", hindi_name: "लोहित" },
    //     { id: 18, name: "Namsai", hindi_name: "नामसाई" },
    //     { id: 19, name: "Changlang", hindi_name: "चांगलांग" },
    //     { id: 20, name: "Tirap", hindi_name: "तिरप" },
    //     { id: 21, name: "Longding", hindi_name: "लोंगडिंग" },
    //   ],
    },
    {
      id: 3,
      name: "Assam",
      hindi_name: "असम",
    },
    {
      id: 4,
      name: "Bihar",
      hindi_name: "बिहार",
    },
    {
      id: 5,
      name: "Chhattisgarh",
      hindi_name: "छत्तीसगढ़",
    },
    {
      id: 6,
      name: "Goa",
      hindi_name: "गोवा",
    },
    {
      id: 7,
      name: "Gujarat",
      hindi_name: "गुजरात",
    },
    {
      id: 8,
      name: "Haryana",
      hindi_name: "हरियाणा",
    },
    {
      id: 9,
      name: "Himachal Pradesh",
      hindi_name: "हिमाचल प्रदेश",
    },
    {
      id: 10,
      name: "Jharkhand",
      hindi_name: "झारखंड",
    },
    {
      id: 11,
      name: "Karnataka",
      hindi_name: "कर्नाटक",
    },
    {
      id: 12,
      name: "Kerala",
      hindi_name: "केरल",
    },
    {
      id: 13,
      name: "Madhya Pradesh",
      hindi_name: "मध्य प्रदेश",
    },
    {
      id: 14,
      name: "Maharashtra",
      hindi_name: "महाराष्ट्र",
    },
    {
      id: 15,
      name: "Manipur",
      hindi_name: "मणिपुर",
    },
    {
      id: 16,
      name: "Meghalaya",
      hindi_name: "मेघालय",
    },
    {
      id: 17,
      name: "Mizoram",
      hindi_name: "मिज़ोरम",
    },
    {
      id: 18,
      name: "Nagaland",
      hindi_name: "नागालैंड",
    },
    {
      id: 19,
      name: "Odisha",
      hindi_name: "ओडिशा",
    },
    {
      id: 20,
      name: "Punjab",
      hindi_name: "पंजाब",
    },
    {
      id: 21,
      name: "Rajasthan",
      hindi_name: "राजस्थान",
    },
    {
      id: 22,
      name: "Sikkim",
      hindi_name: "सिक्किम",
    },
    {
      id: 23,
      name: "Tamil Nadu",
      hindi_name: "तमिलनाडु",
    },
    {
      id: 24,
      name: "Telangana",
      hindi_name: "तेलंगाना",
    },
    {
      id: 25,
      name: "Tripura",
      hindi_name: "त्रिपुरा",
    },
    {
      id: 26,
      name: "Uttar Pradesh",
      hindi_name: "उत्तर प्रदेश",
    },
    {
      id: 27,
      name: "Uttarakhand",
      hindi_name: "उत्तराखंड",
    },
    {
      id: 28,
      name: "West Bengal",
      hindi_name: "पश्चिम बंगाल",
    },
  ];

  module.exports = StatesAndCities;