const express = require("express");
const departmentController = require("./controller/department.Controller");
const attendanceController = require("./controller/attendance.Controller");
const employeeController = require("./controller/employee.Controller");
const leaveController = require("./controller/leave.Controller");
const permissionController = require("./controller/permission.Controller");
const roleController = require("./controller/role.Controller");
const payrollController = require("./controller/payroll.Controller");
const performanceController = require("./controller/performance.Controller");
const userController = require("./controller/user.Controller");
const branchController = require("./controller/branch.Controller");
const designationController = require("./controller/designation.Controller");
const documentTypeController = require("./controller/documentType.Controller");
const awardTypeController = require("./controller/awardType.Controller");
const awardController = require("./controller/award.Controller");
const promotionController = require("./controller/promotion.Controller");
const resignationController = require("./controller/resignation.Controller");
const terminationController = require("./controller/termination.Controller");
const performanceIndicatorCategoryController = require("./controller/performanceIndicatorCategory.Controller");
const performanceIndicatorController = require("./controller/performanceIndicator.Controller");
const performanceGoalTypeController = require("./controller/performanceGoalType.controller");
const goalController = require("./controller/goal.Controller");
const reviewCycleController = require("./controller/reviewCycle.controller");
const employeeReviewController = require("./controller/employeeReview.controller");
const warningController = require("./controller/warning.controller");
const tripController = require("./controller/trip.controller");
const complaintController = require("./controller/complaint.controller");
const transferController = require("./controller/transfer.controller");
const holidayController = require("./controller/holiday.controller");
const announcementController = require("./controller/announcement.controller");
const salaryComponentController = require("./controller/salaryComponent.controller");
const employeeSalaryController = require("./controller/employeeSalary.controller");
const payrollRunController = require("./controller/payrollRun.controller");
const jobCategoryController = require("./controller/jobCategory.controller");
const jobRequisitionController = require("./controller/jobRequisition.controller");
const jobTypeController = require("./controller/jobType.controller");
const jobLocationController = require("./controller/jobLocation.controller");


const router = express.Router();

router.use("/department", departmentController);
router.use("/attendance", attendanceController);
router.use("/employee", employeeController);
router.use("/leave", leaveController);
router.use("/permission", permissionController);
router.use("/role", roleController);
router.use("/payroll", payrollController);
router.use("/performance", performanceController);
router.use("/user", userController);
router.use("/branch", branchController);
router.use("/designation", designationController);
router.use("/document-type", documentTypeController);
router.use("/award-type", awardTypeController);
router.use("/award", awardController);
router.use("/promotion", promotionController);
router.use("/resignation", resignationController);
router.use("/termination", terminationController);
router.use("/indicator-category", performanceIndicatorCategoryController);
router.use("/indicator", performanceIndicatorController);
router.use("/goal-type", performanceGoalTypeController);
router.use("/goal", goalController);
router.use("/review-cycle", reviewCycleController);
router.use("/employee-review", employeeReviewController);
router.use("/warning", warningController);
router.use("/trip", tripController);
router.use("/complaint", complaintController);
router.use("/transfer", transferController);
router.use("/holiday", holidayController);
router.use("/announcement", announcementController);
router.use("/salary-component", salaryComponentController);
router.use("/employee-salary", employeeSalaryController);
router.use("/payroll-run", payrollRunController);
router.use("/job-category", jobCategoryController);
router.use("/job-requisition", jobRequisitionController);
router.use("/job-type", jobTypeController);
router.use("/job-location", jobLocationController);

module.exports = router;