const express = require("express");
const departmentController = require("./controller/departmentController");
const employeeController = require("./controller/employeeController");
const permissionController = require("./controller/permissionController");
const roleController = require("./controller/roleController");
const payrollController = require("./controller/payrollController");
const performanceController = require("./controller/performanceController");
const userController = require("./controller/userController");
const branchController = require("./controller/branchController");
const designationController = require("./controller/designationController");
const documentTypeController = require("./controller/documentTypeController");
const awardTypeController = require("./controller/awardTypeController");
const awardController = require("./controller/awardController");
const promotionController = require("./controller/promotionController");
const resignationController = require("./controller/resignationController");
const terminationController = require("./controller/terminationController");
const performanceIndicatorCategoryController = require("./controller/performanceIndicatorCategoryController");
const performanceIndicatorController = require("./controller/performanceIndicatorController");
const performanceGoalTypeController = require("./controller/performanceGoalTypeController");
const goalController = require("./controller/goalController");
const reviewCycleController = require("./controller/reviewCycleController");
const employeeReviewController = require("./controller/employeeReviewController");
const warningController = require("./controller/warningController");
const tripController = require("./controller/tripController");
const complaintController = require("./controller/complaintController");
const transferController = require("./controller/transferController");
const holidayController = require("./controller/holidayController");
const announcementController = require("./controller/announcementController");
const salaryComponentController = require("./controller/salaryComponentController");
const employeeSalaryController = require("./controller/employeeSalaryController");
const payrollRunController = require("./controller/payrollRunController");
const jobCategoryController = require("./controller/jobCategoryController");
const jobRequisitionController = require("./controller/jobRequisitionController");
const jobTypeController = require("./controller/jobTypeController");
const jobLocationController = require("./controller/jobLocationController");
const adminController = require("./controller/adminController");
const jobPostingController = require("./controller/jobPostingController");
const candidateSourceController = require("./controller/candidateSourceController");
const candidateController = require("./controller/candidateController");
const meetingTypeController = require("./controller/meetingTypeController");
const leaveTypeController = require("./controller/leaveTypeController");
const leavePolicyController = require("./controller/leavePolicyController");
const leaveApplicationController = require("./controller/leaveApplicationController");
const leaveBalanceController = require("./controller/leaveBalanceController");
const shiftController = require("./controller/shiftController");
const attendancePolicyController = require("./controller/attendancePolicyController");
const attendanceRecordController = require("./controller/attendanceRecordController");
const attendanceRegularizationController = require("./controller/attendanceRegularizationController");
const meetingRoomController = require("./controller/meetingRoomController");
const meetingController = require("./controller/meetingController");

const router = express.Router();

router.use("/department", departmentController);
router.use("/employee", employeeController);
router.use("/permission", permissionController);
router.use("/role", roleController);
router.use("/payroll", payrollController);
router.use("/performance", performanceController);
router.use("/user", userController);
router.use("/branch", branchController);
router.use("/designation", designationController);
router.use("/document-type", documentTypeController);
router.use("/award-type", awardTypeController);
router.use("/award", awardController);
router.use("/promotion", promotionController);
router.use("/resignation", resignationController);
router.use("/termination", terminationController);
router.use("/indicator-category", performanceIndicatorCategoryController);
router.use("/indicator", performanceIndicatorController);
router.use("/goal-type", performanceGoalTypeController);
router.use("/goal", goalController);
router.use("/review-cycle", reviewCycleController);
router.use("/employee-review", employeeReviewController);
router.use("/warning", warningController);
router.use("/trip", tripController);
router.use("/complaint", complaintController);
router.use("/transfer", transferController);
router.use("/holiday", holidayController);
router.use("/announcement", announcementController);
router.use("/salary-component", salaryComponentController);
router.use("/employee-salary", employeeSalaryController);
router.use("/payroll-run", payrollRunController);
router.use("/job-category", jobCategoryController);
router.use("/job-requisition", jobRequisitionController);
router.use("/job-type", jobTypeController);
router.use("/job-location", jobLocationController);
router.use("/admin", adminController);
router.use("/job-posting", jobPostingController);
router.use("/candidate-source", candidateSourceController);
router.use("/candidate", candidateController);
router.use("/meeting-type", meetingTypeController);
router.use("/meeting-room", meetingRoomController);
router.use("/meeting", meetingController);
router.use("/leave-type", leaveTypeController);
router.use("/leave-policy", leavePolicyController);
router.use("/leave-application", leaveApplicationController);
router.use("/leave-balance", leaveBalanceController);
router.use("/shifts", shiftController);
router.use("/attendance-policy", attendancePolicyController);
router.use("/attendance-record", attendanceRecordController);
router.use("/attendance-regularization", attendanceRegularizationController);

module.exports = router;
